<?php

namespace RobinIngelbrecht\PHPUnitPrettyPrint;

class Quotes
{
    private const QUOTES = [
        'Every SQL statement that Chuck Norris codes has an implicit "COMMIT" in its end.',
        'Chuck Norris can write multi-threaded applications with a single thread.',
        'Chuck Norris is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.',
        'Chuck Norris insists on strongly-typed programming languages.',
        "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up.",
        'The class object inherits from Chuck Norris',
        'Chuck Norris does not code in cycles, he codes in strikes.',
        "If you Google search \"Chuck Norris getting his ass kicked\" you will generate zero results. It just doesn't happen.",
        "When Chuck Norris throws exceptions, it's across the room.",
        "Chuck Norris can't test for equality because he has no equal.",
        "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS.",
        "Chuck Norris doesn't use web standards as the web will conform to him.",
        '"It works on my machine" always holds true for Chuck Norris.',
        'Everybody thinks the Galaxy Note 7 is explosive. In fact it is only Chuck Norris who tries to send a WhatsApp message with a selfie to his fans.',
        "Chuck Norris doesn't need to use AJAX because pages are too afraid to postback anyways.",
        "Chuck Norris doesn't need sudo, he just types \"Chuck Norris\" before his commands.",
        'Chuck Norris can access the DB from the UI.',
        "Chuck Norris' programs never exit, they terminate.",
        'If Chuck Norris writes code with bugs, the bugs fix themselves.',
        'To Chuck Norris, everything contains a vulnerability.',
        "Chuck Norris doesn't use GUI, he prefers COMMAND line.",
        'Chuck Norris is currently suing myspace for taking the name of what he calls everything around you.',
        'Chuck Norris can write infinite recursion functions and have them return.',
        'Chuck Norris solved the halting problem.',
        "Chuck Norris's log statements are always at the FATAL level.",
        "Chuck Norris doesn't need an OS.",
        'Chuck Norris invented the internet? just so he had a place to store his porn.',
        'Chuck Norris does infinit loops in 4 seconds.',
        "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts.",
        "Chuck Norris's first program was kill -9.",
        "Chuck Norris's keyboard has the Any key.",
        "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.",
        'Chuck Norris breaks RSA 128-bit encrypted codes in milliseconds.',
        "No one has ever spoken during review of Chuck Norris' code and lived to tell about it.",
        'Project managers never ask Chuck Norris for estimations... ever.',
        'Chuck Norris protocol design method has no status, requests or responses, only commands.',
        'Chuck Norris went out of an infinite loop.',
        "Chuck Norris doesn't use Oracle, he is the Oracle.",
        'Chuck Norris does not need to know about class factory pattern. He can instantiate interfaces.',
        "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise.",
        'Chuck Norris can instantiate an abstract class.',
        'The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.',
        "MySpace actually isn't your space, it's Chuck Norris's (he just lets you use it).",
        'All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.',
        'Chuck Norris does not need to type-cast. The Chuck Norris-Compiler sees through things. All the way down. Always.',
        "Chuck Norris's beard can type 140 wpm.",
        "There is no Esc key on Chuck Norris' keyboard, because no one escapes Chuck Norris.",
        'No statement can catch the ChuckNorrisException.',
        'Chuck Norris hosting is 101% uptime guaranteed.',
        'Chuck Norris is the ultimate mutex, all threads fear him.',
        'Chuck Norris programs do not accept input.',
        "A diff between your code and Chuck Norris's is infinite.",
        "When Chuck Norris breaks the build, you can't fix it, because there is not a single line of code left.",
        "Google won't search for Chuck Norris because it knows you don't find Chuck Norris, he finds you.",
        "If you try to kill -9 Chuck Norris's programs, it backfires.",
        'Chuck Norris can install iTunes without installing Quicktime.',
        "Don't worry about tests, Chuck Norris's test cases cover your code too.",
        'Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick).',
        'For Chuck Norris, NP-Hard = O(1).',
        'The only pattern Chuck Norris knows is God Object.',
        'All browsers support the hex definition #chuck and #norris for the colors black and blue.',
        'The Chuck Norris Eclipse plugin made alien contact.',
        'Chuck Norris compresses his files by doing a flying round house kick to the hard drive.',
        "Chuck Norris originally appeared in the \"Street Fighter II\" video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, Norris replied \"That's no glitch.\"",
        'Chuck Norris uses canvas in IE.',
        "Chuck Norris doesn't use reflection, reflection asks politely for his help.",
        'Chuck Norris writes code that optimizes itself.',
        'Chuck Norris can dereference NULL.',
        "Chuck Norris doesn't need a debugger, he just stares down the bug until the code confesses.",
        'Chuck Norris programs occupy 150% of CPU, even when they are not executing.',
        'Chuck Norris can solve the Towers of Hanoi in one move.',
        'When Chuck Norris is web surfing websites get the message "Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?".',
        'Chuck Norris can binary search unsorted data.',
        "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
        "Chuck Norris can retrieve anything from \/dev\/null.",
        'Chuck Norris can unit test entire applications with a single assert.',
        "Chuck Norris doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().",
        "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris.",
        "Chuck Norris's programs can pass the Turing Test by staring at the interrogator.",
        'Chuck Norris can access private methods.',
        "Chuck Norris' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
        'Chuck Norris can compile syntax errors.',
        'Chuck Norris knows the last digit of PI.',
        'Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest.',
        'Chuck Norris burst the dot com bubble.',
        'No one has ever pair-programmed with Chuck Norris and lived to tell about it.',
        "Chuck Norris doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking.",
        "Chuck Norris's OSI network model has only one layer - Physical.",
        "Chuck Norris's database has only one table, 'Kick', which he DROPs frequently.",
        'Chuck Norris can spawn threads that complete before they are started.',
        'Chuck Norris finished World of Warcraft.',
        "Chuck Norris doesn't pair program.",
        "Chuck Norris solved the Travelling Salesman problem in O(1) time. Here's the pseudo-code: Break salesman into N pieces. Kick each piece to a different city.",
        'Chuck Norris can delete the Recycling Bin.',
        'Chuck Norris can overflow your stack just by looking at it.',
    ];

    public static function getRandom(): string
    {
        return self::QUOTES[array_rand(self::QUOTES)];
    }

    /**
     * @return string[]
     */
    public static function getAll(): array
    {
        return self::QUOTES;
    }
}
